// Code generated by MockIO. DO NOT EDIT.
// Source: sample/mockio/interface.go

// Package mockio_foo is a generated GoMock package.
package mockio_foo

import (
	foo "github.com/golang/mock/sample/mockio"
)

type Get struct {
	Time   int
	ArgFoo int
	ArgBar string
	Ret0   foo.Model
	Ret1   error
}

type List struct {
	Time    int
	ArgFoos []int
	ArgBars []string
	Ret0    []foo.Model
	Ret1    error
}
